export const REGISTER_STUDENT = "REGISTER_STUDENT";
export const REGISTER_TUTOR = "REGISTER_TUTOR";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_STUDENT = "LOGIN_STUDENT";
export const LOGIN_TUTOR = "LOGIN_TUTOR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const STUDENT_LOADED = "STUDENT_LOADED";
export const TUTOR_LOADED = "TUTOR_LOADED";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const UPDATE_TUTOR = "UPDATE_TUTOR";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const GET_TUTOR_DETAILS = "GET_TUTOR_DETAILS";

export const LOGOUT = "LOGOUT";

export const AUTH_START_LOADING = "AUTH_START_LOADING";
export const AUTH_STOP_LOADING = "AUTH_STOP_LOADING";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
